### ISSUE TITLE
Belted Z Bodies

### ISSUE THREAD

**Issue by arteuspw** [Pole-Engineering/Crossant-235#20]
Needs some kind of brace. flexes a bit when motor is tensioned. 

![Image](https://github.com/Pole-Engineering/Crossant-235/assets/53056781/41924616-c3ca-4228-a272-5ad29101c9d4)

**Comment by YamacGN** [comment]
fixed with https://github.com/Pole-Engineering/Crossant-235/commit/86b5152044a450875aa5b6d5418f6c23d4abbe7f
