### ISSUE TITLE
Kinematic Z Joints (Belted)

### ISSUE THREAD

**Issue by arteuspw** [Pole-Engineering/Crossant-235#21]
![Image](https://github.com/Pole-Engineering/Crossant-235/assets/53056781/abeea785-1725-4ac3-b57b-d742184504d6)

![Image](https://github.com/Pole-Engineering/Crossant-235/assets/53056781/71954095-553e-44fc-b71a-eeb08ae0bb8b)

**Comment by YamacGN** [comment]
Fixed with https://github.com/Pole-Engineering/Crossant-235/commit/a191d741356131e7dd3c28f6ec8cc897ec849e52
