### ISSUE TITLE
Panels

### ISSUE THREAD

**Issue by arteuspw** [Pole-Engineering/Crossant-235#24]
- Belted Z panel is missing holes

**Comment by YamacGN** [comment]
Fixed with https://github.com/Pole-Engineering/Crossant-235/commit/4ca449062d06fcf87869bf81b118c58dc23c2de6

**Comment by YamacGN** [comment]
Fixed with https://github.com/Pole-Engineering/Crossant-235/commit/a191d741356131e7dd3c28f6ec8cc897ec849e52
